In [3]:
# Before we start...
# http://www.numpy.org/
import numpy

In [4]:
# Generating numbers
arange = numpy.arange(15)

print(arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [5]:
# Creating an array from a range
array = arange.reshape(3,5)
print(array)

# Getting the transposed array
print(numpy.transpose(array))
print(array.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [6]:
# Or maybe with another shape
array = arange.reshape(5,3)
print(array)

# Getting the transposed array
print(array.T)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]


In [7]:
# But I don't want a dynamic array!
array = numpy.array(1,2,3)

# THIS WON'T WORK

ValueError: only 2 non-keyword arguments accepted

In [8]:
# Not it will work!
array = numpy.array([[1,2,3]])

print(array)
print(array.T)


array = numpy.array([[1,2,3], [4,5,6]])

print(array)
print(array.T)

[[1 2 3]]
[[1]
 [2]
 [3]]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [9]:
# Cool stuff
print(numpy.zeros((3,5)))

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
